mercure:
    hubs:
        default:
            #url: '%env(MERCURE_URL)%'
            #public_url: '%env(MERCURE_PUBLIC_URL)%'
            url: 'http://localhost:3000/.well-known/mercure'
            public_url: 'http://localhost:3000/.well-known/mercure'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
