version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "63153:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
      - "3000:3000"
###< symfony/mercure-bundle ###
